### ISSUE TITLE
An error occurred while performing the image captcha.

### ISSUE THREAD

**Issue by LUORANCHENG** [LanLan69/easyChatGPT#2]
D:\python_env\chatgpt_python\lib\site-packages\pydub\utils.py:170: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
  warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)
D:\python_env\chatgpt_python\lib\site-packages\pydub\utils.py:198: RuntimeWarning: Couldn't find ffprobe or avprobe - defaulting to ffprobe, but may not work
  warn("Couldn't find ffprobe or avprobe - defaulting to ffprobe, but may not work", RuntimeWarning)
Traceback (most recent call last):
  File "D:\python_project\easyChatGPT-main\examples\test.py", line 10, in <module>
    chat = ChatClient(OPENAI_EMAIL,OPENAI_PASSWORD)
  File "D:\python_project\easyChatGPT-main\src\easychatgpt\chatgpt.py", line 44, in __init__
    self.__login(username, password)
  File "D:\python_project\easyChatGPT-main\src\easychatgpt\chatgpt.py", line 77, in __login
    is_checked = reCaptchaV2(self.browser, play=False)  # it returns bool
  File "D:\python_env\chatgpt_python\lib\site-packages\pypasser\reCaptchaV2\__init__.py", line 70, in __new__
    raise e
  File "D:\python_env\chatgpt_python\lib\site-packages\pypasser\reCaptchaV2\__init__.py", line 55, in __new__
    file_path = convert_to_wav(download_audio(link))
  File "D:\python_env\chatgpt_python\lib\site-packages\pypasser\utils.py", line 42, in convert_to_wav
    AudioSegment.from_mp3(file_path).export(wav_file_path, format='wav')
  File "D:\python_env\chatgpt_python\lib\site-packages\pydub\audio_segment.py", line 796, in from_mp3
    return cls.from_file(file, 'mp3', parameters=parameters)
  File "D:\python_env\chatgpt_python\lib\site-packages\pydub\audio_segment.py", line 728, in from_file
    info = mediainfo_json(orig_file, read_ahead_limit=read_ahead_limit)
  File "D:\python_env\chatgpt_python\lib\site-packages\pydub\utils.py", line 274, in mediainfo_json
    res = Popen(command, stdin=stdin_parameter, stdout=PIPE, stderr=PIPE)
  File "d:\.pyenv\pyenv-win\versions\3.9.0\lib\subprocess.py", line 947, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "d:\.pyenv\pyenv-win\versions\3.9.0\lib\subprocess.py", line 1416, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

**Comment by LanLan69** [comment]
得下载ffmpeg和ffprobe。好像这个必须得自己下载。https://bbc.github.io/bbcat-orchestration-docs/installation-windows/
这个是教程
